# Generated by Django 5.1.7 on 2025-10-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='repuestos_utilizados',
        ),
        migrations.AddField(
            model_name='tarea',
            name='repuestos_utilizados_desc',
            field=models.TextField(blank=True, verbose_name='Repuestos Utilizados'),
        ),
    ]
