# Generated by Django 5.2.6 on 2025-09-30 00:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenimientos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Repuesto',
                'verbose_name_plural': 'Categorías de Repuestos',
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo_compatible', models.CharField(blank=True, max_length=200, verbose_name='Modelo Compatible')),
                ('stock_actual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Actual')),
                ('stock_minimo', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Mínimo')),
                ('stock_maximo', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Máximo')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('bajo_stock', 'Bajo Stock'), ('agotado', 'Agotado'), ('descontinuado', 'Descontinuado')], default='disponible', max_length=20)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Costo')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('ubicacion_bodega', models.CharField(blank=True, max_length=100, verbose_name='Ubicación en Bodega')),
                ('codigo_barras', models.CharField(blank=True, max_length=100, verbose_name='Código de Barras')),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('tiempo_reposicion', models.IntegerField(default=7, help_text='Días estimados para reposición', verbose_name='Tiempo de Reposición')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.categoriarepuesto', verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pedido', models.CharField(max_length=50, unique=True, verbose_name='Código de Pedido')),
                ('cantidad_solicitada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cantidad_recibida', models.IntegerField(default=0)),
                ('proveedor', models.CharField(max_length=200)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ordenado', 'Ordenado'), ('parcial', 'Recibido Parcialmente'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_estimada_entrega', models.DateField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_solicitados', to=settings.AUTH_USER_MODEL)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('transferencia', 'Transferencia')], max_length=20)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('motivo', models.TextField()),
                ('numero_documento', models.CharField(blank=True, max_length=100, verbose_name='Número de Documento')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_anterior', models.IntegerField()),
                ('stock_posterior', models.IntegerField()),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='mantenimientos.tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_fisica', models.IntegerField(verbose_name='Cantidad Física')),
                ('cantidad_sistema', models.IntegerField(verbose_name='Cantidad en Sistema')),
                ('diferencia', models.IntegerField(verbose_name='Diferencia')),
                ('motivo', models.CharField(choices=[('diferencia_fisica', 'Diferencia Física'), ('robo', 'Robo o Pérdida'), ('dano', 'Daño o Deterioro'), ('caducidad', 'Caducidad'), ('conteo_fisico', 'Conteo Físico'), ('otro', 'Otro')], max_length=20)),
                ('motivo_otro', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_ajuste', models.DateTimeField(auto_now_add=True)),
                ('fecha_conteo', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.repuesto')),
            ],
        ),
    ]
