# Generated by Django 5.1.7 on 2025-10-12 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0002_rename_observaciones_documentovehiculo_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(help_text='Patente del vehículo (ej. ABC123)', max_length=10)),
                ('fecha_hora', models.DateTimeField(help_text='Fecha y hora de la cita')),
                ('duracion_minutos', models.PositiveIntegerField(default=60, help_text='Duración estimada en minutos')),
                ('tipo_mantencion', models.CharField(choices=[('preventiva', 'Mantención Preventiva'), ('correctiva', 'Reparación Correctiva'), ('neumaticos', 'Cambio de Neumáticos'), ('dpf', 'Limpieza DPF'), ('bateria', 'Reemplazo de Batería'), ('otro', 'Otro')], default='preventiva', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Cita de Mantenimiento',
                'verbose_name_plural': 'Citas de Mantenimiento',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
