# Generated by Django 5.2.6 on 2025-09-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pausa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('espera_repuesto', 'Espera de Repuesto'), ('consultas_tecnicas', 'Consultas Técnicas'), ('revision_supervisor', 'Revisión de Supervisor'), ('problema_calidad', 'Problema de Calidad'), ('falta_herramienta', 'Falta de Herramienta'), ('reunion_operativa', 'Reunión Operativa'), ('descanso', 'Descanso'), ('almuerzo', 'Almuerzo'), ('otro', 'Otro')], max_length=50)),
                ('motivo_otro', models.CharField(blank=True, max_length=100)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('pausada', 'Pausada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tiempo_estimado', models.IntegerField(default=60, help_text='Tiempo estimado en minutos')),
                ('repuestos_utilizados', models.TextField(blank=True)),
                ('observaciones_finales', models.TextField(blank=True)),
            ],
        ),
    ]
