# Generated by Django 5.1.7 on 2025-10-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('jefe_taller', 'Jefe de Taller'), ('mecanico', 'Mecánico'), ('chofer', 'Chofer'), ('vendedor', 'Vendedor/Preventista'), ('guardia', 'Guardia'), ('bodeguero', 'Bodeguero'), ('ehs', 'EHS')], default='mecanico', max_length=20),
        ),
    ]
