# Generated by Django 5.2.8 on 2025-11-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('jefe_taller', 'Jefe de Taller'), ('mecanico', 'Mecánico'), ('chofer', 'Chofer'), ('vendedor', 'Vendedor/Preventista'), ('guardia', 'Guardia'), ('bodeguero', 'Bodeguero'), ('ehs', 'EHS'), ('coordinador_zona', 'Coordinador de Zona'), ('recepcionista', 'Recepcionista de Vehículos'), ('supervisor_flota', 'Supervisor de Flota'), ('encargado_llaves', 'Encargado de Llaves')], default='mecanico', max_length=30),
        ),
    ]
