# Generated by Django 5.2.8 on 2025-11-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('jefe_taller', 'Jefe de Taller'), ('mecanico', 'Mecánico'), ('chofer', 'Chofer'), ('vendedor', 'Vendedor/Preventista'), ('guardia', 'Guardia'), ('bodeguero', 'Bodeguero'), ('ehs', 'EHS'), ('recepcionista', 'Recepcionista de Vehículos')], default='mecanico', max_length=30),
        ),
    ]
