# Generated by Django 5.2.6 on 2025-09-29 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('tipo_vehiculo', models.CharField(choices=[('camion', 'Camión'), ('furgon', 'Furgón'), ('pickup', 'Pickup'), ('automovil', 'Automóvil'), ('maquinaria', 'Maquinaria')], max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('numero_chasis', models.CharField(blank=True, max_length=50)),
                ('kilometraje', models.IntegerField(default=0)),
                ('nombre_chofer', models.CharField(max_length=100)),
                ('telefono_chofer', models.CharField(max_length=15)),
                ('empresa_chofer', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('ingresado', 'Ingresado'), ('diagnostico', 'En Diagnóstico'), ('reparacion', 'En Reparación'), ('listo', 'Listo para Retiro'), ('entregado', 'Entregado')], default='ingresado', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('motivo_ingreso', models.TextField()),
                ('observaciones_ingreso', models.TextField(blank=True)),
                ('guardia_ingreso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_ingresados', to=settings.AUTH_USER_MODEL)),
                ('mecanico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=50)),
                ('archivo', models.FileField(upload_to='documentos_vehiculos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='vehiculos.vehiculo')),
            ],
        ),
    ]
