# Generated by Django 5.2.6 on 2025-09-30 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentovehiculo',
            old_name='observaciones',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='documentovehiculo',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentovehiculo',
            name='nombre_archivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documentovehiculo',
            name='subido_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentovehiculo',
            name='tipo_documento',
            field=models.CharField(choices=[('permiso_circulacion', 'Permiso de Circulación'), ('seguro_soap', 'Seguro SOAP'), ('revision_tecnica', 'Revisión Técnica'), ('foto_ingreso', 'Foto de Ingreso'), ('foto_salida', 'Foto de Salida'), ('informe_siniestro', 'Informe de Siniestro'), ('orden_trabajo', 'Orden de Trabajo'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_siniestro', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_siniestro', models.DateTimeField()),
                ('lugar_siniestro', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('reportado', 'Reportado'), ('en_evaluacion', 'En Evaluación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('completado', 'Completado')], default='reportado', max_length=20)),
                ('compañia_seguro', models.CharField(blank=True, max_length=100)),
                ('numero_poliza', models.CharField(blank=True, max_length=100)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siniestros_evaluados', to=settings.AUTH_USER_MODEL)),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siniestros_reportados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to='vehiculos.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='FotoSiniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='siniestros/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_toma', models.DateTimeField(auto_now_add=True)),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='vehiculos.siniestro')),
            ],
        ),
    ]
