# Generated by Django 5.1.7 on 2025-10-19 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_rename_observaciones_documentovehiculo_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='chofer_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'chofer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_como_chofer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='mecanico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_como_mecanico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='nombre_chofer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='telefono_chofer',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
