# Generated by Django 5.2.7 on 2025-11-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_vehiculo_chofer_asignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='flota',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='kilometraje',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('camion', 'Camión'), ('camion_dts', 'Camión DTS'), ('camion_cstore', 'Camión Cstore'), ('furgon', 'Furgón'), ('pickup', 'Pickup'), ('automovil', 'Automóvil'), ('maquinaria', 'Maquinaria'), ('funcional_flota', 'Funcional Flota'), ('merchandising', 'Merchandising')], max_length=50),
        ),
    ]
