# Generated by Django 5.2.7 on 2025-11-25 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_vehiculo_activo_vehiculo_flota_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('ingresado', 'Ingresado'), ('diagnostico', 'En Diagnóstico'), ('reparacion', 'En Reparación'), ('listo', 'Listo para Retiro'), ('entregado', 'Entregado'), ('rechazado', 'Ingreso Rechazado')], default='ingresado', max_length=20),
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada al Taller'), ('salida', 'Salida del Taller')], max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('nombre_chofer', models.CharField(max_length=100)),
                ('telefono_chofer', models.CharField(blank=True, max_length=15)),
                ('empresa_chofer', models.CharField(blank=True, max_length=100)),
                ('kilometraje', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Daños visibles, estado general, etc.')),
                ('foto_vehiculo', models.ImageField(blank=True, null=True, upload_to='acceso_vehiculos/')),
                ('autorizado_por', models.ForeignKey(blank=True, help_text='Jefe de taller o mecánico que autoriza la salida', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('guardia', models.ForeignKey(limit_choices_to={'rol': 'guardia'}, on_delete=django.db.models.deletion.PROTECT, related_name='registros_acceso_realizados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_acceso', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
